[fakeiot]
broadcast_interval = 10000
mqtt_ids = [
  'fakeiot-1',
  'fakeiot-2',
  'fakeiot-3',
  'fakeiot-4',
  'fakeiot-5',
  'fakeiot-6',
  'fakeiot-8',
  'fakeiot-9',
  'fakeiot-10',
]

[mqtt]
endpoint = 'tcp://localhost:18830'
qos = 1
topic = 'fakeiot/sensors'
